### ISSUE TITLE
Spool holder part problems

### ISSUE THREAD

**Issue by poyaque-estamos** [prusa3d/Prusa-i3-Plus#1]
Hi!

The stl for the spool holder doesn't match the one that comes with the printer. It doesn't have holes in it to save plastic when printing out. Also, there are not two versions for each side of it, just one. These problems are also seemly present in the scad file, considering the dxf doesn't have the holes and there are no comments in the scad file to get right-left version.

**Comment by poyaque-estamos** [comment]
I have fixed the problem with left and right spool holder myself, in the scad file, but the holes would be nice to get from your model. I'll add it as a pull request.

**Comment by poyaque-estamos** [comment]
Seems the left and right arms for the spool holder are included in the mk2 branch. Good! Still no holes on the dxf and therefore the stl files.

**Comment by prusa3d-bb** [comment]
Hello,
yes, I added it to MK2 branch. Supplied spool holders are now shipped without holes so it’s consistent with our manufacturing process.
If you want the spool holder with holes, please use attached dxf and replace it with MK3 version.

—
Michal Průša, CTO
