### ISSUE TITLE
Can you please share the R3 scad or step files too

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/Prusa-i3-Plus#100]
Thanks for the MK3 upgraded R3 STL files but can you also please share the scad or step files as well?

**Comment by stahlfabrik** [comment]
Hi Gussner, some (or all?!) scad files have been shared earlier.

**Comment by 3d-gussner** [comment]
@stahlfabrik thanks for the info.
@veverkaondrej Thanks for uploading

Close issue
