### ISSUE TITLE
Newest STL files unable to download.

### ISSUE THREAD

**Issue by beneq69** [prusa3d/Prusa-i3-Plus#101]
Newest STL files for Prusa MK3 are unable to download and print Only Einsy-base is available

**Comment by stahlfabrik** [comment]
I can download the zip file - and all new stl files are in it. The openscad files are not updated though, but that is another issue

**Comment by beneq69** [comment]
Original-Prusa-i3/Printed-Parts/stl/ files added yesterday.

**Comment by stahlfabrik** [comment]
Yes. What is the issue?

**Comment by beneq69** [comment]
So ill ask different way. Which program i have to use to open that new stl files? I tried Slicer and Simplify3D and after downloaded files i can only files: "Z-axis-bottom", "Einsy-base", "x-end-motor", "x-carriage". All others new files I can't open.

**Comment by stahlfabrik** [comment]
That is strange, I tried to open X-end-idler in Slic3r. Works like a charm. Also the Y motor holder works just fine. I guess that you have a corrupted file?!

**Comment by stahlfabrik** [comment]
So have you downloaded the zip file?

**Comment by beneq69** [comment]
Yes, Download one more time couple minutes ego and I can open files right now. Thank You for help
