### ISSUE TITLE
Minor tweak to remove "loose end" on Mk3s extruder body.

### ISSUE THREAD

**Issue by Mjankor** [prusa3d/Prusa-i3-Plus#124]
Not sure if I did this changing nozzle, or whether it happened due to radiant heat, but the loose end of the extruder-cover.stl, near where it meets the Pinda mount drooped down on my (polycarbonate) extruder. 

On the old Mk3 extruder, this loose end was supported by the Pinda mount on the extruder body. It may be worth having a small tab that links to the pinda mount on the extruder body. 
![screen shot 2019-03-01 at 7 45 17 pm](https://user-images.githubusercontent.com/17077516/53628789-e305a800-3c5b-11e9-905a-8fbef29c5759.png)
![screen shot 2019-03-01 at 7 45 08 pm](https://user-images.githubusercontent.com/17077516/53628790-e305a800-3c5b-11e9-8f0e-d4a315b1f2ae.png)

**Comment by Mjankor** [comment]
I've added it to my Mk3h extruder body. Feel free to incorporate that into the main design. Also, there's a very thin walled section in the centre of that surface between the top cutout and the bottom ridgeline. Might be worth shifting the start of the cutout outwards, away from the e3D, a bit.
https://www.thingiverse.com/thing:3431164

**Comment by ServeurpersoCom** [comment]
I have this part that systematically melt on the official MK3S parts.
Now I remove entirely this useless lose end.

**Comment by Prusa-Support** [comment]
Thank you for the report. The extruder parts have been redesigned for the MK3S+ and this issue should be fixed now. I am therefore closing this issue as solved.

Marek Micek
Prusa Research
