### ISSUE TITLE
hardware stops heating waiting for inserts... operator asleep 17 hour print... I need to continue the print... how?

### ISSUE THREAD

**Issue by carterm2** [prusa3d/Prusa-i3-Plus#125]
Prusa I3 Mk3 3.6.0
Latest Slicr3

I am trying to find out how to finish the last 5% of a print after a heater stop... please read to find out the situation.

...
In Slic3r Prusa... I added an M600 to my print, with the plus button....

<img width="287" alt="screen shot 2019-03-07 at 7 41 55 am" src="https://user-images.githubusercontent.com/11826844/53968895-b4009380-40ac-11e9-832c-6266e1f83c11.png">

I inserted the recommended text, from another Prusa Forum Post...

https://shop.prusa3d.com/forum/others-archive--f82/pause-print-in-gcode-t2034.html#p125758

 in a text editor... inplace of M600

M300 ;ACTIVATE BEEPER
G1 X10.000 Y200.000; parking position GET THE PRUSA TO STICK IT'S TONGUE OUT!
M1; user stop
G28 Y
M105; return to current temp

This stops the print, beeps, moves the extruder to the back left side of the printed, sets up a resume/cancel button on my OctoPrint screen, rehomes Y, and is supposed to....

Return to print temperature.

But I was asleep, and the printer turned of the heat for safety... I forgot the error message on the Prusa Screen

Q1
How can I start the print for the last 5%... Homing Z with the Panda probe will knock the part off the bed...

Q2
Can I replace the M600 text with my own in Slic3r?

Thanks,

Carter

**Comment by tobymurray** [comment]
This repo is for the printer parts - I imagine you'll find a bit more traction on https://github.com/prusa3d/Prusa-Firmware (the repo for the software that actually executes on the printer).

**Comment by Prusa-Support** [comment]
Since this issue is over 3 years old now and actually doesn't belong to this repo, I will be closing it now.

Marek Micek
Prusa Research
