### ISSUE TITLE
endstop-block.stl corrupt?

### ISSUE THREAD

**Issue by sarf2k4** [prusa3d/Prusa-i3-Plus#127]
Hi,
I am unable to load endstop-block.stl and I believe it is corrupted. I'm unable to load into cura 3, slic3rpe, simplify3d, meshmixer and stlviewer as all of them would throw an error

**Comment by draeath** [comment]
No such issue here for me, and the file hasn't been updated since Feb 27. I'm able to open the .stl in Slic3r PE, and able to import it into Blender 2.79.

This issue looks to be on your end.

**Comment by sarf2k4** [comment]
still the same issue opening the exact file
![image](https://user-images.githubusercontent.com/9604217/57178237-f6253600-6e9f-11e9-8427-6640d08aceeb.png)

**Comment by bubnikv** [comment]
would you please attach the file here?

**Comment by sarf2k4** [comment]
here it is, downloaded using latest forefox to this writing date
[endstop-block.zip](https://github.com/prusa3d/Original-Prusa-i3/files/3144541/endstop-block.zip)

**Comment by bubnikv** [comment]
it is a html document, not an stl.

**Comment by sarf2k4** [comment]
Sorry, I was using "save link as" instead of downloading the whole zip, model loaded correctly
