### ISSUE TITLE
[Proposal] FABUI

### ISSUE THREAD

**Issue by infinity0n3** [prusa3d/Prusa-i3-Plus#143]
I'm making a new UI for 3d printers and CNC machines.
It's an highly optimized printer control running on raspberry pi with a nice web interface.

There is an initial support for i3 MK2 printers.

You can check it out [on GitLab](https://gitlab.com/colibri-embedded/fabui)

MK2.5 and MK3/S are in the list but have not been tested well yet so MK2 is the suggested printer to try it out on.

**Comment by origel** [comment]
Great! can you show me some screen shots?

**Comment by infinity0n3** [comment]
Sure, there are [screenshots](https://gitlab.com/colibri-embedded/fabui/fabui-frontend/-/wikis/screenshots) now on the wiki page.

**Comment by tracernz** [comment]
That looks excellent! The obvious missing thing is webcam support. Do you have any plans in that area?

**Comment by infinity0n3** [comment]
@tracernz There are several things planned after the alpha phase is finished. Like camera support, gcode preview. For now the focus is to get everything working and on multiple printers and to add milling support and grbl gcode flavor support.

**Comment by Prusa-Support** [comment]
We are launching our own remote control software Prusa Connect.
https://connect.prusa3d.com/ (currently in Beta)
Works with Prusa Link - Raspberry Pi based interface for MK3S/+ - https://github.com/prusa3d/Prusa-Link-Web

Marek Micek
Prusa Research
