### ISSUE TITLE
[Question] Is READMEmd outdated?

### ISSUE THREAD

**Issue by jarl-dk** [prusa3d/Prusa-i3-Plus#147]
In the README to this repo it says:

> Original Prusa i3 MK2
> 
> Original Prusa i3 MK2 is a 3D printer project maintained by PRUSA RESEARCH. Originates in RepRap project.

But I believe the parts are for i3MK3-series.

And link to the product links to MK2, but is redirected to MK3

Is the README outdate? The parts are good for i3MK3, right?

**Comment by jarl-dk** [comment]
Ahh. I see, it seems like there is a branch for each printer model...

**Comment by tracernz** [comment]
Yes. Maybe it would be a good idea to make MK3S the default branch.

**Comment by jarl-dk** [comment]
I don't think that the branching feature of a version control system is the best way to separate different products, variants or models.

**Comment by Moorviper** [comment]
It is not a different product.
All printers are the i3.
you can also use mk3 parts on the mk2 or vice versa.
