### ISSUE TITLE
Slic3r 1.3.0 not opening LCD_cover.stl

### ISSUE THREAD

**Issue by masquerain0601** [prusa3d/Prusa-i3-Plus#150]
As i said in the title i can't open this file with Slic3r (not prusa Slic3r) it is in a loop, loading but it does not goes any further. I tried opening all other files and there are no issue

https://github.com/prusa3d/Original-Prusa-i3/blob/MK2/Printed-Parts/stl/LCD_cover.stl

**Comment by Moorviper** [comment]
And you are really sure it is a bug of prusa and the ticket belongs to this repo ?

**Comment by BNoiZe** [comment]
I just tried to open the file in Slic3r myself. It is opening without problem. So I am certain this is a problem with Slic3r on your system. So I think this report belongs to the Slic3r repo.

**Comment by Moorviper** [comment]
![Bildschirmfoto 2020-06-15 um 16 21 55](https://user-images.githubusercontent.com/3305254/84668863-6962fd80-af24-11ea-85df-b63a385306de.png)
Yes works fine

**Comment by masquerain0601** [comment]
Ok so it is a problem of my installation :/
Thank you
