### ISSUE TITLE
einsy-base file and others missing in STEP

### ISSUE THREAD

**Issue by artur-panek** [prusa3d/Prusa-i3-Plus#153]
I've noticed that many files are missing in .STP format. I'm especially looking for einsy-base.stp .

**Comment by 3d-gussner** [comment]
It is there https://www.github.com/prusa3d/Original-Prusa-i3/tree/MK3S/Printed-Parts%2FSTEP%2Fextruder-body.stp

You need to change the github branch for different models.

**Comment by artur-panek** [comment]
Hi, you just showed me the extruder-body.stp and I'm looking for einsy-base.stp.

**Comment by 3d-gussner** [comment]
> Hi, you just showed me the extruder-body.stp and I'm looking for einsy-base.stp.

Sorry for wrong link.
Glad you found it.

**Comment by 3d-gussner** [comment]
Please close this issue.

**Comment by artur-panek** [comment]
I haven't found it yet.

**Comment by Exeu** [comment]
@3d-gussner @artur-panek and where it is now? im also looking for it...

**Comment by artur-panek** [comment]
@Exeu Still not there.

**Comment by bwees** [comment]
These files still do not exist. What is the reason for these files missing??
