### ISSUE TITLE
SCAD files missing from MK3S branch

### ISSUE THREAD

**Issue by gargan26** [prusa3d/Prusa-i3-Plus#156]
Several SCAD files are missing from the MK3S branch.  In the spirit of open-source, I'd like to see all *original* source CAD files used to generate the most current production parts here. (I.E., SCAD, Solidworks, Inventor, etc...)

Has anybody spoken with Prusa directly about getting these source CAD files?

**Comment by Moorviper** [comment]
You have to go through the branches to get all.
Or which one is missing ?

**Comment by 6ffm70** [comment]
I'd look here: https://github.com/prusa3d/Original-Prusa-i3/tree/MK3S/Printed-Parts/SCAD
Which ones are missing?

**Comment by Prusa-Support** [comment]
As mentioned in #163 , if the part has been designed in OpenSCAD, then a SCAD file is provided. If it was designed in other modeling software, we provide STEP file, which can be imported and edited in many 3D modeling programs.

Marek Micek
Prusa Research
