### ISSUE TITLE
PINDA_protector.stl off-size and missing SCAD

### ISSUE THREAD

**Issue by pboschi** [prusa3d/Prusa-i3-Plus#16]
The PINDA_protector.stl is reportedly too big. Needs to be sliced at exactly 96%. The SCAD file is also missing, so it's not possible to check where's the error.

Also check here:
http://shop.prusa3d.com/forum/original-prusa-i3-mk2-f23/mk2-p-i-n-d-a-protector-woes-t1663.html

**Comment by ryanneufeld** [comment]
bump

**Comment by diggit** [comment]
still problem, I had to scale current protector stl to 93% to fit on PINDA

**Comment by bardiir** [comment]
The PINDA Protector also doesn't seem to fit the MK2S version mounted PINDA at all, even if sliced with 93%

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
