### ISSUE TITLE
[Question] Why do some nozzles types have such low torque setting as 1.5Nm?

### ISSUE THREAD

**Issue by mop999x** [prusa3d/Prusa-i3-Plus#160]
i have a mk3s and having some nozzle issues so i did some research due to nozzle leaks and was wondering why prusa/e3d suggest to use 2.5-3Nm (i believed this to be universal for all nozzle types regardless of manufacture) torque on nozzle to tighten it but other sources i found mostly for other nozzle types (Tungsten carbide) suggest torque of no more then 1.5NM, here are few examples

https://docs.dyzedesign.com/nozzles.html#install-your-tungsten-carbide-nozzle

and i believe even 3d maker engendering says the same

do you know why that is?

i just wanted to know why tightening nozzle at 3NM that say 1.5Nm would cause a leak, if it would ?

![signal-2020-11-23-133646](https://user-images.githubusercontent.com/74934080/100028172-f358a180-2db3-11eb-8043-1973b5fcf65b.jpeg)

**Comment by tomavisar** [comment]
What does this have to do with this? Also it's because different materials have different levels of thermal expansion

**Comment by Prusa-Support** [comment]
Hello! 
I am sorry for the late response to this thread. We can think of the nozzle as any bolt, so depending on the bolt at hand the manufacturer specifies a maximum torque to be applied. If we apply too much torque, we'd have a risk of damaging, deforming, stripping the bolt, which can result in a loose joint. Leaking filament from above the heater block is a result of a loose joint between nozzle and heatbreak. 

So in this case, the too much torque could have caused deformation, stripping, which might have led to a poor joint nozzle-heatbreak which causes the leaking. I'd recommend checking if also using the correct torque spec would not solve the issue - in that case, the loose joint would be likely caused, provided that nozzle and heatbreak are compatible, by a badly positioned heatbreak (can be inadvertently raised during the nozzle change procedure). 

Alessandro Pantaleo
Prusa Research
