### ISSUE TITLE
Some parts only available as SCAD

### ISSUE THREAD

**Issue by miracuruzrh** [prusa3d/Prusa-i3-Plus#163]
Hi everyone

I wonder why some parts are only available as SCAD files and not as STEP files?
For example x-carriage and x-carriage back are not available as STEP file.
I try export the files from openscad to CSG format and then import it to freecad to generate a STEP file which is a pain.
Therefore it would be nice if someone have the parts available as STEP and could upload it?

**Comment by Prusa-Support** [comment]
We provide the source files for the parts in the original format they were created in. If the part has been modeled in OpenSCAD, then there is only the SCAD file available. If the part has been created or edited in some other modeling software (Autodesk Inventor, etc.), which is the case for many new parts for MK3S/S+, then an editable STEP file is provided.

Marek Micek
Prusa Research
