### ISSUE TITLE
MK3S front frame plate modification

### ISSUE THREAD

**Issue by terryjphillips** [prusa3d/Prusa-i3-Plus#180]
Two "U" shaped slots in the front frame plate would allow the Y-axis rods to be removed to make lubing the bearings easy.
![IMG_0753](https://user-images.githubusercontent.com/48333674/148567743-01288497-00b4-4501-81ca-f68d8d4e14d1.JPG)

**Comment by Prusa-Support** [comment]
Hello,
thank you for your suggestion. We currently have no plans to make further changes to the metal parts of the printer. The proposed change would have very little benefit. The rods, if needed, can be easily removed by unscrewing the plastic Y-rod holders.

Marek Micek
Prusa Research
