### ISSUE TITLE
Problems with extruder models

### ISSUE THREAD

**Issue by tkircher** [prusa3d/Prusa-i3-Plus#21]
The extruder body and cover models both have issues where holes don't go all the way through. This is true of both the SCAD files and the generated STLs currently in the repository. Increasing the Z-axis lengths of the appropriate cylinders in extruder-main.scad solves these problems.

Also, the bearing support shaft, which fits into the extruder idler, doesn't exist in the repository. However, it did come included with the Prusa i3 mk2 kit and is an essential part. I'd be happy to provide patches for both of these issues.

Edit: There's also an issue with the y-corners SCAD and STL. Some fixes attached.
[prusa_fixes.zip](https://github.com/prusa3d/Original-Prusa-i3/files/820401/prusa_fixes.zip)

**Comment by ryanneufeld** [comment]
This was done intentionally. Since you can't print circles in mid-air. Just use a 3mm drill-bit and clean out the holes

**Comment by tkircher** [comment]
I had no trouble printing these on my Prusa. If you're having issues, it's better to print with a slightly tapered hole using a conical cutout than to require unnecessary post-processing. I've done that on several designs that had too much gap to bridge reliably, and cap screws still seat perfectly well.

**Comment by ryanneufeld** [comment]
I am some explaining it. I am not even a contributor.

**Comment by tkircher** [comment]
Normally I would just make my own fork, but the missing parts, at the very least, should get addressed here. There are other things like the reinforced Y stage motor mount that should probably also get included in the main repository.

**Comment by akukan** [comment]
Explained, by design
