### ISSUE TITLE
MK2S Rambo cover design problem

### ISSUE THREAD

**Issue by tjhawkey** [prusa3d/Prusa-i3-Plus#28]
The part has a design problem so the first layer doesn't print well. There's a big cutout, then it's covered on subsequent layers.
![image](https://cloud.githubusercontent.com/assets/18601538/25303724/d2fec082-2726-11e7-8852-0524b27d4136.png)

**Comment by bubnikv** [comment]
This has been done on purpose to ease the material pile-up common to PET
filaments. The gaps are filled from the top by bridges when slicing with
Slic3r.

**Comment by tjhawkey** [comment]
That's clever. I figured out how to comment out some lines in the scad file and get a clean printout. Works fine with the particular filament I'm using.

Thanks for explaining!
