### ISSUE TITLE
Discussion Tab

### ISSUE THREAD

**Issue by tbedore** [prusa3d/Prusa-i3-Plus#32]
This will serve as a way to get direct communication with developers at Prusa Research, I need to talk to some developers over there about the development of the Prusa i3 MK2 3d printer.

**Comment by diggit** [comment]
[There is forum for discussions](http://shop.prusa3d.com/forum/). Be more specific to get reply.

**Comment by boelle** [comment]
@tbedore & @diggit and maybe close this one as it does not serve a purpose anymore??
