### ISSUE TITLE
MMU parts missing the new extruder adapter model

### ISSUE THREAD

**Issue by liftoff** [prusa3d/Prusa-i3-Plus#35]
The MMU .stl and .scad files are still the old design with two screws for the PINDA probe.  I just received my MMU and wanted to print the latest spare parts.  That's when I noticed the new design is missing.

Specifically, I'm referring to `extruder-adaptor-mm.stl` and `extruder-adaptor-mm.scad` in the Multi-Material-Upgrade branch.

**Comment by akukan** [comment]
Parts updated

**Comment by liftoff** [comment]
Just wanted to say thanks!  I appreciate it.  Going to print the new extruder adapter ASAP 👍
