### ISSUE TITLE
Are these the parts for the MK2.5 as well, or are there differences?

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Prusa-i3-Plus#38]
Hi

Just wondering if the MK3 has the same parts as the MK2.5? My MK2 works wonderfully, but I would really like to use quieter fans like on the MK3 and MK2.5.

Thanks

**Comment by mloidl** [comment]
Same question for me.
I've already ordered the MK2.5 upgrade kit and want to print the new parts during the x-mas holidays.

**Comment by akukan** [comment]
Parts for MK2.5 upgrade available in 2.5 branch. Please check list - parts different from MK3 are in branch 2.5, parts that are same as MK3 please take from MK3 branch. These ( 2.5 ) are final, but there is always some probability that they might change once finally upgrade is released.
