### ISSUE TITLE
No scad files for LCD support a/b

### ISSUE THREAD

**Issue by ManuGithubSteam** [prusa3d/Prusa-i3-Plus#4]
Hi

There is no scad file for the LCD-support "arms" a and b. 

I would like to make a shorter version of the arms (shorter in length) so that the printer fits into the Ikea LACK enclosure (50cm max) but you have to make walls so you are left with 49 cm at best and that is not enough as the cables from the heatbed also need space.

In short, if you would make the lcd-support arms not so long and around 1cm shorter it would solve the issue. But as i can not find the scad files i can not attempt to do that myself.

Thanks
Manuel

**Comment by akukan** [comment]
Files uploaded and available.
