### ISSUE TITLE
Power supply electronics base SCAD source missing

### ISSUE THREAD

**Issue by fiveangle** [prusa3d/Prusa-i3-Plus#41]
Any idea when the MK3 power supply electronics base SCAD source files will be up ?  I want to get it modified for rear-exit of the NEMA-15 [like I did for the MK2/MK2S](https://www.thingiverse.com/thing:1942906), so it will be ready when my kit arrives :)

Thanks,

-=dave

**Comment by prusa3d-bb** [comment]
Hi there,

I just forwarded this message to our developers. They will take a look at it :)

Best regards


—
Tomáš Chvalina
Technical Support


PRUSA Research
+420 222 263 718 
+421 220 570 305
Partyzánská 188/7A, 170 00 Praha 

shop.prusa3D.com

--- original message ---
On Mon, Dec 11, 2017 at 09:02 am, <notifications@github.com> Dave Johnson wrote:


Any idea when the power supply electronics base SCAD source files will be up ? I want to get it modified for rear-exit of the NEMA-15 like I did for the MK2/MK2S, so it will be ready when my kit arrives :)

Thanks,

-=dave

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by erikcramerjr** [comment]
Any update on this, im still missing the files.

**Comment by fiveangle** [comment]
Too busy making Extruder Motor Visualizers perhaps ? 😉

**Comment by fiveangle** [comment]
Can someone please provide clarification as to why source for this part is not available ?

**Comment by nicw** [comment]
I'd be interested in this as well. I'm assuming there is some legal concern around releasing this because it's the power supply, or does Prusa consider this part to be their own intellectual property?

**Comment by jltx1** [comment]
I am eagerly awaiting fiveangle's rear-exit modification, so please post the scad files.  Thank you.

**Comment by gregsaun** [comment]
As others, I would like to use the SCAD/STL file for my [project](https://github.com/gregsaun/prusa_i3_bear_upgrade). Any news?

**Comment by maximlevitsky** [comment]
Any update? :-)

**Comment by cnschu** [comment]
i contacted support a few eeeks ago about this issue, but other than "i'll forward it", no fix so far.

**Comment by fiveangle** [comment]
3 months later and nothing.  This should have been an explicitly easy-to-fulfill request since they continue to ship this part with every printer.    With an entire quarter of a year come and gone with no action, and at least one other unanswered request for the same in #60, it is difficult to conclude anything other than this is intentionally and knowingly being ignored.  The question is why ?  If they deciced to not release just this part under GPL like the rest of the printer, why not just state so instead of ignore the community ?

Anyway, I've executed on an alternate solution and have no further need for this personally so have half a mind to close this issue, but will leave open if others want me to continue pursuit.

-=dave

**Comment by lecktor** [comment]
Today, I was at Prusa Research office and asked the same... so basically in 15 minutes I've received stl files to my email. Adding files to here... (A9 version)
[PSU_cover_MK3.zip](https://github.com/prusa3d/Original-Prusa-i3/files/1885211/PSU_cover_MK3.zip)

**Comment by fiveangle** [comment]
zip contains STL so now that there is proof of them distributing binaries, I guess they are now on the hook for the source (I guess like Creality3D : )

-=dave

**Comment by 3d-gussner** [comment]
@fiveangle Hi Dave, I am not sure that the hardware parts are under any GPL.
Prusa is so kind to share them and have been used by so many other companies, which don't share any files.

But they provided the STL files now so they would have followed the rules as you can reproduce the part. You have the 'source' code to reproduce the part you got.

CAD programs can be used to modify the part if you want. There is no need to provide the SCAD files even it would be great to have them.

**Comment by fiveangle** [comment]
@3d-gussner - I suggest you review how the GPL works, and the license present in the repository for the MK3:

https://github.com/prusa3d/Original-Prusa-i3/blob/MK3/LICENSE

Binaries is not the same as source code.  Yes, you can modify STL just like you can try and disassemble firmware, but it is not the same as access to the source code which the GPL guarantees.

I don't even personally need this part any longer, but the spirit of open source software is being flouted, which is surprising for such a pillar of the RepRap community as Prusa Research is.  I mention all of this only out of principle and I'm surprised others here are accepting of this.

How can we expect companies such as Creality3D to honor the GPL when our most beloved and beneficial commercial venture in the community cannot do the same ?

-=dave

**Comment by ManuGithubSteam** [comment]
@fiveangle You have a valid point there! I remember that i did download the source for the mk2s and there was also a folder with scad files. So at some point they released the mk2 source.

I attach the source files here:
https://drive.google.com/open?id=1R9tPsnpWZKzqlQPsWTE4ByGqfn2H1AZL

I will probably hold on to them a while longer, seen the reluctance to relase the source of the mk3.....

**Comment by fiveangle** [comment]
@ManuGithubSteam - the MK2S SCAD source is published in this very repo in the MK2S branch:

https://github.com/prusa3d/Original-Prusa-i3/tree/MK2S/Printed-Parts/scad

-=dave

**Comment by akukan** [comment]
Both STL and SCAD files for psu cover are published now. Sorry for terrible delay, shortly, the main reason ( same as with MK2 version during release ) was concerns regarding people working in area where they can do something wrong in 110/220 V installation.

**Comment by maximlevitsky** [comment]
I must really say thanks to you, even though I won't probably be printing this cover for now.
I am really happy to see all the parts open and that is what especially makes Prusa such a great printer.
Thank you!!

**Comment by fiveangle** [comment]
smh

-=dave

**Comment by fiveangle** [comment]
Oh the irony…

![5678903F-02FC-46B1-8D80-51E1CAA34B74](https://user-images.githubusercontent.com/2219447/180038942-79bf23e5-d609-433d-bc0b-81231fb7e017.jpeg)

https://twitter.com/josefprusa/status/1548294406746148867
