### ISSUE TITLE
Missing MK2.5 RAMBo cover hinges?

### ISSUE THREAD

**Issue by gregsaun** [prusa3d/Prusa-i3-Plus#43]
Hi Prusa team,

I was checking the new RAMBo covers that comes with MK2.5, looks like a nice "hidden" update! The new door is 2mm thinner (18mm instead of 20mm on MK2s) and the top hinge hole looks a bit different. I was then surprised to not see new hinges for MK2.5, are they missing?

**Comment by akukan** [comment]
Stl file was missing, updated :-)
