### ISSUE TITLE
Jog dial/button SLT missing

### ISSUE THREAD

**Issue by FDillon00** [prusa3d/Prusa-i3-Plus#46]
Ordered an MK3 (can't wait) but I wanted to change the color of the button and can't seem to find the SLT. Thanks

**Comment by Moorviper** [comment]
it is the same like the mk2 knob you can use it from this branch

**Comment by bvarner** [comment]
Where might I find the scad source for the knob?

**Comment by Moorviper** [comment]
https://github.com/prusa3d/Original-Prusa-i3/

**Comment by bvarner** [comment]
@moorviper I see the stl...but where’s the scad?

**Comment by Moorviper** [comment]
in the main branch

**Comment by bvarner** [comment]
I have to admit, I wasn’t expecting g the scad to say “import the stl.”

I was expecting the scad to be able to generate the stl...

**Comment by gregsaun** [comment]
This has been fixed, we can close

**Comment by Prusa-Support** [comment]
This issue will be closed due to it being obsolete.

Marina Curzi
Prusa Research
