### ISSUE TITLE
Feature request: Setting for LCD screen to 'sleep' after 5 mins

### ISSUE THREAD

**Issue by mrjohnc** [prusa3d/Prusa-i3-Plus#6]
It would be nice to have this option, especially for printing at night when the screen can be very bright

**Comment by ManuGithubSteam** [comment]
I second this! I also asked support about it. It would be good to turn it off into "night" mode so only a knob turn turns it back on for a few seconds.

**Comment by bubnikv** [comment]
Yeah! That would be great! Only the current hardware does not support this.

**Comment by mrjohnc** [comment]
Ok, thanks @bubnikv, shame its not possible. Is it the particular screens that are shipped or the controller board?

**Comment by ManuGithubSteam** [comment]
Would it be possible to turn it off completely ?

**Comment by mrjohnc** [comment]
Ah yes, this would be good, maybe an option in settings for 'display sleep after 5 minutes'? and any movement in the dial would turn the brightness back on again.

**Comment by bubnikv** [comment]
If you know which side of the soldering iron is hot, you can surely
disconnect the display or add a manual switch to the backlight. But to
control it by the software is another thing, you would need to add a data
line from the RAMBo to the displa, add a transistor and likely a resistor
or two. It is doable, but not that easy.

**Comment by mrjohnc** [comment]
@bubnikv so this could not be done by software alone?

**Comment by bubnikv** [comment]
That is correct. It cannot be controlled by the software alone. You have to do some soldering job on the display board.

**Comment by mrjohnc** [comment]
Ok, hopefully a display capable of this will be added to future versions of the kit

**Comment by boelle** [comment]
i think its safe to close this one as the hardware is not able to do it.

and it has been so for a year and its very unlikely to change anytime soon
