### ISSUE TITLE
Missing MK3 PSU cover 

### ISSUE THREAD

**Issue by libxmike** [prusa3d/Prusa-i3-Plus#60]
I'm missing here SCAD/STL for PSU cover, can you add it?

**Comment by fiveangle** [comment]
Dupe of #41 (and yes, it would be nice if they would post the file)

**Comment by stahlfabrik** [comment]
Fixed now!

**Comment by Prusa-Support** [comment]
The SCAD for the PSU cover has been added.

Marina Curzi
Prusa Research
