### ISSUE TITLE
Nylon filament could damage cables on MK2.5 RAMBo base

### ISSUE THREAD

**Issue by gregsaun** [prusa3d/Prusa-i3-Plus#67]
The nylon filament we have to insert on the RAMBo base could go too deep during build and damage cables inside the RAMBo base (during the build or later due to vibration). Nylon filament hole should be closed on the internal side of the RAMBo base.

**Comment by Panayiotis-git** [comment]
Even though a hole exists to insert the nylon filament, the manual instructs that:
> "The nylon filament stays as a part of the bundle. No need to separate it as on the older versions of the RAMBo cover."
So, the hole should not be used.

**Comment by gregsaun** [comment]
That is a god point, thanks. I close the issue then :-)
