### ISSUE TITLE
MK3 Smooth rod sizes

### ISSUE THREAD

**Issue by unixb0y** [prusa3d/Prusa-i3-Plus#80]
I would really appreciate a little PDF similar to the one for the Aluminium extrusions with official dimensions for the smooth rods that are used in the MK3.
Can’t seem to find official information as the instructions don’t state the lengths. 
Thank you in advance !

**Comment by Panayiotis-git** [comment]
Check the assembly guides.

**Comment by unixb0y** [comment]
@Panayiotis-git you’re right, the current version does include lengths for X and Y, but the Z axis rod length isn’t specified.

**Comment by Panayiotis-git** [comment]
You are right.
Look here. I've checked earlier and they are at correct lengths:
http://zaribo.org/smooth-rods/54-original-prusa-mk3mk2s-8mm-smooth-rod-kit-by-misumi.html

**Comment by unixb0y** [comment]
Thanks! 2x320 2x330 2x370 👌🏼
