### ISSUE TITLE
MK3 heat break has step that accumulates filament and causes jams

### ISSUE THREAD

**Issue by matthew-humphrey** [prusa3d/Prusa-i3-Plus#81]
The Prusa-designed E3D heat break on i3 MK3 printers has a "step" inside the tube. This step extrusion problems including jams and broken filament. 

See the attached photo for a picture from a microscope of my heat break. The area in focus is some Prusa translucent green PETG that has accumulated in the step. This contamination was causing jams and poor print quality. I was unable to remove it even with repeated cold pulls.

![kingprusaheatbreak](https://user-images.githubusercontent.com/5487637/42112610-3f120574-7b9d-11e8-9272-c558127ccb99.jpg)

**Comment by Crunch69** [comment]
that explains the jams I keep having isnt the e3d heatbreak suppose to be smooth that is what they advertise

**Comment by Zaf9670** [comment]
I have my heat break apart at home. I will take a look to see if mine has the same knot.

**Comment by c-stewart** [comment]
Correct me if I'm wrong but I believe that Prusa gets custom heartbreaks
from E3D that include this difference, to be compatible with the multi
material upgrade.

**Comment by murphy2712** [comment]
I believe it was only useful for MMU v1, which is retired now.

**Comment by c-stewart** [comment]
Right, but it wasn't when they started shipping mk3's. So the question is,
is this the same thing or something different?

**Comment by Zaf9670** [comment]
I did not notice the step/knot in my heatbreak but I may have needed more light. I just got done replacing my heatbreak with the E3D Titanium.

**Comment by matthew-humphrey** [comment]
It looks like the heatbreaks they are shipping now no longer have the problem. Many of us who got printers earlier do have this issue, though.

**Comment by Crunch69** [comment]
when did prusa switch back to the stock e3d heat break?

**Comment by matthew-humphrey** [comment]
I don't know if it's stock or just correctly machined not to have that step. I can confirm that replacing the Prusa HB with a genuine E3D resolved my issue.

**Comment by ThaliaFP** [comment]
At which height is the step? Where the PTFE tube ends in the heat sink or where the heatsink and the nozzle come together?
![heat break](https://user-images.githubusercontent.com/28732158/43673112-19c9a614-97bd-11e8-8e48-8853e2fd61ff.jpg)

**Comment by matthew-humphrey** [comment]
It's actually right in the middle of the heatbreak. micro-swiss heatbreak has one as well, by the way.
