### ISSUE TITLE
Missing: Fan Duct

### ISSUE THREAD

**Issue by 0x736E** [prusa3d/Prusa-i3-Plus#82]
I recently had an issue where I had to replace my Fan Duct due to a failed print which damaged mine.

I went here first to find it, and found that the fan duct was missing from the repository. After contacting support, I got a copy of the file from the prusa website, but this seems like a glaring omission to me.

Please add the fan duct to this repo. #

**Comment by stahlfabrik** [comment]
It is there. Nozzle fan or so it is called

**Comment by 0x736E** [comment]
That's not been updated for the Mk3 style fan though.

compare: https://imgur.com/a/F0Trj3H

**Comment by 0x736E** [comment]
just noticed I was looking at the Mk2 branch. my mistake.
