### ISSUE TITLE
SCAD files missing for new MK3 extruder improvements

### ISSUE THREAD

**Issue by matthew-humphrey** [prusa3d/Prusa-i3-Plus#84]
Prusa recently posted some updates to the MK3 extruder designed to improve hotend cooling and print cooling. There are STL files posted, but no equivalent SCAD files.

The STL files are:

1. Printed-Parts/stl/extruder-body-v2.stl
2. Printed-Parts/stl/extruder-cover-v2.stl
3. Printed-Parts/stl/nozzle-fan-45deg.stl
4. Printed-Parts/stl/nozzle-fan-45deg-support.stl

**Comment by uepsie** [comment]
STEPs would be even nicer :-)

**Comment by matthew-humphrey** [comment]
Sounds like maybe Prusa is moving away from OpenSCAD (yay!). If so, it would be great to get the source files in whatever format they are in.

**Comment by Psyc0Flyer** [comment]
I agree also with having the native files for at least the Extruder body and cover. There are many improvements for the Coanda Effect that can be implemented!

**Comment by c-stewart** [comment]
The 2 new non binary STL's state that they're still made in openscad at
least. (On the first and last line)

**Comment by jiri-jirus** [comment]
step files are now present. :(

**Comment by jiri-jirus** [comment]
hey, @josefprusa can you comment on this?

**Comment by matthew-humphrey** [comment]
I'm closing this since, as pointed out in the replies above, the STEP files are now available. 

As someone who spent several hours working around bugs in the Freecad openscad import just so I could convert one part (Einsy-base), I would be thrilled if Prusa started using Solid Works or Fusion 360 or some other cad tool with a more portable format.

**Comment by ghost** [comment]
Very sad turnaround for Prusa to abandon OpenSCAD and go for a proprietary solution.

**Comment by infosisio** [comment]
@josefprusa You are an open project, how can you use proprietary software for the files?
