### ISSUE TITLE
Filament Runout sensor?

### ISSUE THREAD

**Issue by np22-jpg** [prusa3d/Prusa-i3-Plus#98]
Instead of using a PINDA probe or an optical laser to detect filament, why not use a wheel and 2 bearings with a magnetic encoder such as an AS5047P to detect the filament? It can detect speed and the presence of the filament easily, as long as its moving. This shouldn't matter with any of the printer's functions.

**Comment by Moorviper** [comment]
Then you have to set the  wheel for each filament. 
the laser is a good way.
I am currently building my own multimaterial device (uses 2 laser mouse sensor and detect in addition the filament by color by another sensor.
It also checks under the nozzle if the color is clean and then wipe the nozzle  with a brush.
Then i need no purge tower or wipe into infill on my printers.

**Comment by ManuGithubSteam** [comment]
I sencond the laser :-)

**Comment by np22-jpg** [comment]
Why does it need to be set for each filament? It can be like other printers, using a spring-loaded idler gear. As long as the wheel spins and matches the desired extrusion rate, it should be okay. I don't see how the as5047p (not the as5601 lol) would react any different to a flexible than PLA.

**Comment by np22-jpg** [comment]
The only thing I do see, however, is the cost. It is heavier and costs 10x as much for this setup rather than a laser. Also, lasers throw out false positives.

**Comment by Moorviper** [comment]
I got two prusa laser sensor clones for around 5€ inkl shipping i don't think you are getting much cheaper.
The cheapest magnetic encoder on digikey is around 4,5€ alone

But do it more options are always good

**Comment by bdynamic** [comment]
@Moorviper Could you maybe share your source? Ali has them for about 11$...

**Comment by Moorviper** [comment]
Yes now there was a sale week last week.
actually it cost 8,47€/$9,80 ok -80% within the app was a good deal

**Comment by jltx1** [comment]
My fix:
https://www.thingiverse.com/thing:3091625 <https://www.thingiverse.com/thing:3091625>

**Comment by np22-jpg** [comment]
That defeats the point of why I opened this issue, however. The PINDA probe cant detect jams.
